Repository URECA-TEAM-5/PopFlix-backend, pull requests merged in 2024-12, with the labels that each got.

#58 Feat: 영화 필드 추가
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/dto/GetMovieListResponseDto.java
  src/main/java/com/popflix/domain/movie/service/MovieService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
Labels: 🚀 Refactor

#62 feat : 로그인, 로그아웃, 회원가입 기능 구현
  build.gradle
  src/main/java/com/popflix/auth/config/JwtConfig.java
  src/main/java/com/popflix/auth/controller/AuthController.java
  src/main/java/com/popflix/auth/dto/OAuthProviderInfo.java
  src/main/java/com/popflix/auth/dto/ProfileImage.java
  src/main/java/com/popflix/auth/dto/TokenDto.java
  src/main/java/com/popflix/auth/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/popflix/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/popflix/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/popflix/auth/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/popflix/auth/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/com/popflix/auth/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/popflix/auth/service/AuthService.java
  src/main/java/com/popflix/auth/token/JwtTokenFilter.java
  src/main/java/com/popflix/auth/token/TokenProvider.java
  src/main/java/com/popflix/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/popflix/common/log/entity/ActivityLog.java
  src/main/java/com/popflix/common/log/entity/AdminLog.java
  src/main/java/com/popflix/common/log/enums/ActivityType.java
  src/main/java/com/popflix/domain/user/controller/UserRegistrationController.java
  src/main/java/com/popflix/domain/user/dto/UserDto.java
  src/main/java/com/popflix/domain/user/dto/UserRegistrationDto.java
  src/main/java/com/popflix/domain/user/entity/User.java
  src/main/java/com/popflix/domain/user/entity/UserGenre.java
  src/main/java/com/popflix/domain/user/enums/AuthType.java
  src/main/java/com/popflix/domain/user/enums/Role.java
  src/main/java/com/popflix/domain/user/exception/DuplicateEmailException.java
  src/main/java/com/popflix/domain/user/exception/DuplicateNicknameException.java
  src/main/java/com/popflix/domain/user/exception/InvalidGenreException.java
  src/main/java/com/popflix/domain/user/exception/UserNotFoundException.java
  src/main/java/com/popflix/domain/user/repository/UserGenreRepository.java
  src/main/java/com/popflix/domain/user/repository/UserRepository.java
  src/main/java/com/popflix/domain/user/service/UserService.java
  src/main/java/com/popflix/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/popflix/global/config/RedisConfig.java
  src/main/java/com/popflix/global/config/SwaggerConfig.java
  src/main/java/com/popflix/global/service/S3Service.java
Labels: ✨ Feat

#63 feat : 회원 정보 수정, 회원 탈퇴 기능 구현
  src/main/java/com/popflix/auth/controller/AuthController.java
  src/main/java/com/popflix/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/popflix/domain/user/controller/UserController.java
  src/main/java/com/popflix/domain/user/controller/UserRegistrationController.java
  src/main/java/com/popflix/domain/user/dto/GenrePatchDto.java
  src/main/java/com/popflix/domain/user/dto/SignUpDto.java
  src/main/java/com/popflix/domain/user/dto/UserDto.java
  src/main/java/com/popflix/domain/user/dto/UserInfoDto.java
  src/main/java/com/popflix/domain/user/dto/UserPatchDto.java
  src/main/java/com/popflix/domain/user/entity/UserGenre.java
  src/main/java/com/popflix/domain/user/repository/UserGenreRepository.java
  src/main/java/com/popflix/domain/user/service/UserService.java
  src/main/java/com/popflix/domain/user/service/impl/UserServiceImpl.java
Labels: ✨ Feat

#65 Feat: 내가 만든 워치리스트 조회 api 구현
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/entity/Movie.java
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/dto/GetMoviePosterResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetMyStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/repository/StorageRepository.java
  src/main/java/com/popflix/domain/storage/service/StorageService.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: ✨ Feat

#66 Feat: 내가 좋아요 누른 워치리스트 목록 조회 api
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/dto/GetLikedStorageInfoResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetLikedStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetMyStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/repository/StorageLikeRepository.java
  src/main/java/com/popflix/domain/storage/repository/StorageRepository.java
  src/main/java/com/popflix/domain/storage/service/StorageService.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: ✨ Feat

#67 refactor : OAuth2 + JWT 보안 강화
  src/main/java/com/popflix/auth/config/JwtConfig.java
  src/main/java/com/popflix/auth/controller/AuthController.java
  src/main/java/com/popflix/auth/dto/TokenDto.java
  src/main/java/com/popflix/auth/exception/AuthExceptionHandler.java
  src/main/java/com/popflix/auth/exception/BlacklistedTokenException.java
  src/main/java/com/popflix/auth/exception/InvalidCookieException.java
  src/main/java/com/popflix/auth/exception/InvalidTokenException.java
  src/main/java/com/popflix/auth/exception/RefreshTokenException.java
  src/main/java/com/popflix/auth/exception/TokenExpiredException.java
  src/main/java/com/popflix/auth/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/popflix/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/popflix/auth/service/AuthService.java
  src/main/java/com/popflix/auth/token/JwtTokenFilter.java
  src/main/java/com/popflix/auth/token/TokenProvider.java
  src/main/java/com/popflix/auth/util/CookieUtil.java
  src/main/java/com/popflix/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/popflix/global/config/RedisConfig.java
  src/main/java/com/popflix/global/config/SwaggerConfig.java
Labels: 🚀 Refactor

#69 refactor : 보안 수정
  src/main/java/com/popflix/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/popflix/auth/token/JwtTokenFilter.java
  src/main/java/com/popflix/auth/token/TokenProvider.java
Labels: 🚀 Refactor

#70 refactor : 로그인 문제 해결
  src/main/java/com/popflix/auth/config/JwtConfig.java
  src/main/java/com/popflix/domain/user/controller/UserController.java
Labels: 🚀 Refactor

#71 feat : 좋아요 수가 많은 순 조회 기능 추가
  src/main/java/com/popflix/domain/photoreview/controller/PhotoReviewCommentController.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewCommentRepository.java
  src/main/java/com/popflix/domain/photoreview/service/PhotoReviewCommentService.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewCommentServiceImpl.java
Labels: ✨ Feat

#72 feat : 리뷰 수 조회 기능
  src/main/java/com/popflix/domain/review/controller/ReviewController.java
  src/main/java/com/popflix/domain/review/repository/ReviewRepository.java
  src/main/java/com/popflix/domain/review/service/ReviewService.java
  src/main/java/com/popflix/domain/review/service/impl/ReviewServiceImpl.java
Labels: ✨ Feat

#73 Refactor: 마이페이지 보관함 조회시 줄거리, 영화 제목 추가
  src/main/java/com/popflix/domain/storage/dto/CreateStorageRequestDto.java
  src/main/java/com/popflix/domain/storage/dto/GetMoviePosterResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetMyStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageCreatorResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageDetail2ResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/entity/Storage.java
Labels: ✨ Feat

#75 refactor : 알림 리팩터링
  src/main/java/com/popflix/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/popflix/domain/notification/entity/Notification.java
  src/main/java/com/popflix/domain/notification/event/dto/ReviewCreatedEvent.java
  src/main/java/com/popflix/domain/notification/event/listener/ReviewEventListener.java
  src/main/java/com/popflix/domain/notification/service/NotificationService.java
  src/main/java/com/popflix/domain/notification/service/impl/NotificationServiceImpl.java
Labels: 🚀 Refactor

#76 refactor : 알림 리팩터링
  src/main/java/com/popflix/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/popflix/domain/notification/entity/Notification.java
  src/main/java/com/popflix/domain/notification/service/impl/NotificationServiceImpl.java
Labels: 🚀 Refactor

#77 Feat: cicd 반영 테스트
  src/main/java/com/popflix/domain/movie/entity/Movie.java
Labels: 🔨 Fix

#79 feat : 알림 목록 조회 기능 구현
  src/main/java/com/popflix/domain/notification/controller/NotificationController.java
  src/main/java/com/popflix/domain/notification/repository/NotificationRepository.java
  src/main/java/com/popflix/domain/notification/service/NotificationService.java
  src/main/java/com/popflix/domain/notification/service/impl/NotificationServiceImpl.java
Labels: ✨ Feat

#82 refactor : SSE와 이메일 알림을 모두 생성하고 전송 기능 구현
  src/main/java/com/popflix/auth/config/JwtConfig.java
  src/main/java/com/popflix/domain/notification/service/impl/NotificationServiceImpl.java
Labels: 🚀 Refactor

#83 Feat: 영화 목록 조회 ( 개봉일 순, 좋아요 순 ) 내림차순으로 정렬 추가
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/entity/Movie.java
  src/main/java/com/popflix/domain/movie/repository/MovieRepository.java
  src/main/java/com/popflix/domain/movie/service/MovieService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: 🚀 Refactor

#84 refactor : SuccessHandler 로그인 수정
  src/main/java/com/popflix/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🚀 Refactor

#85 Feat: 보관함 주차별 인기순 조회
  build.gradle
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/dto/WeeklyTopStorageDto.java
  src/main/java/com/popflix/domain/storage/entity/StorageLike.java
  src/main/java/com/popflix/domain/storage/repository/StorageRepository.java
  src/main/java/com/popflix/domain/storage/service/StorageService.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: ✨ Feat

#86 Refactor: 보관함 개봉 안 된 영화 제외 코드 추가
  .gitignore
  src/main/java/com/popflix/domain/movie/repository/MovieRepository.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
Labels: 🚀 Refactor

#88 Refactor: 보관함 로그인 여부에 따라 조회 결과 변경
  src/main/java/com/popflix/auth/dto/UserInfoDetails.java
  src/main/java/com/popflix/domain/movie/repository/MovieGenreRepository.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieApiServiceImpl.java
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/dto/UpdateStorageRequestDto.java
  src/main/java/com/popflix/domain/storage/entity/Storage.java
  src/main/java/com/popflix/domain/storage/repository/StorageRepository.java
  src/main/java/com/popflix/domain/storage/service/StorageService.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: 🚀 Refactor

#93 Refactor: 별점 같은 점수 등록 시 오류 메시지 클라에 전달
  src/main/java/com/popflix/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/popflix/domain/movie/exception/DuplicateRatingException.java
  src/main/java/com/popflix/domain/movie/service/impl/RatingServiceImpl.java
Labels: 🚀 Refactor

#95 Refactor: multipartfile error 해결
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/dto/CreateStorageRequestDto.java
  src/main/java/com/popflix/domain/storage/dto/GetMyStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageCreatorResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageDetail2ResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/MonthlyTopStorageDto.java
  src/main/java/com/popflix/domain/storage/entity/Storage.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: 🚀 Refactor

#96 Refactor: 보관함 수정 중 소개글, 제목 반영 안됨 해결
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/service/StorageService.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: 🚀 Refactor

#98 Refactor: 영화 검색 후 필드 수정
  src/main/java/com/popflix/domain/movie/dto/GetSearchResultResponseDto.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
Labels: 🚀 Refactor
