Repository URECA-TEAM-5/PopFlix-backend, pull requests merged in 2024-11, with the labels that each got.

#2 refactor : NotificationType, TargetType 추가
  src/main/java/com/popflix/domain/notification/enums/NotificationType.java
  src/main/java/com/popflix/domain/schedule/enums/TargetType.java
Labels: 🚀 Refactor

#6 refactor : BaseSoftDeleteEntity 추가 및 BaseTimeEntity 변경
  src/main/java/com/popflix/common/entity/BaseSoftDeleteEntity.java
  src/main/java/com/popflix/common/entity/BaseTimeEntity.java
  src/main/java/com/popflix/common/entity/CommonCode.java
  src/main/java/com/popflix/common/entity/GroupCode.java
  src/main/java/com/popflix/common/log/entity/ActivityLog.java
  src/main/java/com/popflix/common/log/entity/AdminLog.java
  src/main/java/com/popflix/domain/movie/entity/Cast.java
  src/main/java/com/popflix/domain/movie/entity/Director.java
  src/main/java/com/popflix/domain/movie/entity/Movie.java
  src/main/java/com/popflix/domain/movie/entity/MovieCast.java
  src/main/java/com/popflix/domain/movie/entity/MovieDirector.java
  src/main/java/com/popflix/domain/movie/entity/MovieGenre.java
  src/main/java/com/popflix/domain/movie/entity/MovieLike.java
  src/main/java/com/popflix/domain/movie/entity/Rating.java
  src/main/java/com/popflix/domain/movie/entity/Recommendation.java
  src/main/java/com/popflix/domain/movie/entity/ReviewVideo.java
  src/main/java/com/popflix/domain/notification/entity/Notification.java
  src/main/java/com/popflix/domain/personality/entity/Genre.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReview.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewComment.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewCommentLike.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewLike.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewReply.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewReplyLike.java
  src/main/java/com/popflix/domain/report/entity/Report.java
  src/main/java/com/popflix/domain/review/entity/Comment.java
  src/main/java/com/popflix/domain/review/entity/CommentLike.java
  src/main/java/com/popflix/domain/review/entity/Review.java
  src/main/java/com/popflix/domain/review/entity/ReviewLike.java
  src/main/java/com/popflix/domain/schedule/entity/DeleteSchedule.java
  src/main/java/com/popflix/domain/schedule/enums/TargetType.java
  src/main/java/com/popflix/domain/storage/entity/MovieStorage.java
  src/main/java/com/popflix/domain/storage/entity/Storage.java
  src/main/java/com/popflix/domain/storage/entity/StorageLike.java
  src/main/java/com/popflix/domain/user/entity/UserGenre.java
Labels: 🚀 Refactor

#7 Feat: 영화 별점 추가 api 구현
  src/main/java/com/popflix/PopflixBackendApplication.java
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/dto/AddRatingRequestDto.java
  src/main/java/com/popflix/domain/movie/dto/GetMovieRatingResponseDto.java
  src/main/java/com/popflix/domain/movie/dto/GetRatingResponseDto.java
  src/main/java/com/popflix/domain/movie/entity/Cast.java
  src/main/java/com/popflix/domain/movie/entity/Director.java
  src/main/java/com/popflix/domain/movie/entity/MovieCast.java
  src/main/java/com/popflix/domain/movie/entity/MovieDirector.java
  src/main/java/com/popflix/domain/movie/entity/MovieLike.java
  src/main/java/com/popflix/domain/movie/entity/Rating.java
  src/main/java/com/popflix/domain/movie/repository/DirectorRepository.java
  src/main/java/com/popflix/domain/movie/repository/RatingRepository.java
  src/main/java/com/popflix/domain/movie/repository/UserRepository.java
  src/main/java/com/popflix/domain/movie/service/MovieApiService.java
  src/main/java/com/popflix/domain/movie/service/MovieService.java
  src/main/java/com/popflix/domain/movie/service/RatingService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieApiServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/RatingServiceImpl.java
  src/main/java/com/popflix/global/error/MovieNotFoundException.java
  src/main/java/com/popflix/global/error/UserNotFoundException.java
Labels: ✨ Feat, 🎶 wontfix

#8 Refactor: 영화 별점 평균치 소수점으로 api 구현
  src/main/java/com/popflix/domain/movie/dto/GetMovieRatingResponseDto.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
Labels: 🚀 Refactor

#9 Chore: exception 관련 패키지 이동
  src/main/java/com/popflix/common/exception/GlobalExceptionHandler.java
  src/main/java/com/popflix/domain/movie/exception/MovieNotFoundException.java
  src/main/java/com/popflix/domain/movie/exception/UserNotFoundException.java
Labels: 🚀 Refactor

#10 refactor : GlobalExceptionHandler 위치 이동
  src/main/java/com/popflix/common/exception/handler/GlobalExceptionHandler.java
Labels: 🚀 Refactor

#11 Feat: 영화 좋아요 처리 API 구현
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/entity/Movie.java
  src/main/java/com/popflix/domain/movie/entity/MovieLike.java
  src/main/java/com/popflix/domain/movie/entity/Rating.java
  src/main/java/com/popflix/domain/movie/repository/MovieLikeRepository.java
  src/main/java/com/popflix/domain/movie/repository/RatingRepository.java
  src/main/java/com/popflix/domain/movie/service/MovieLikeService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieLikeServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
Labels: ✨ Feat

#13 feat : 리뷰 기능 구현
  src/main/java/com/popflix/domain/review/controller/CommentController.java
  src/main/java/com/popflix/domain/review/controller/ReviewController.java
  src/main/java/com/popflix/domain/review/dto/CommentPatchDto.java
  src/main/java/com/popflix/domain/review/dto/CommentPostDto.java
  src/main/java/com/popflix/domain/review/dto/CommentResponseDto.java
  src/main/java/com/popflix/domain/review/dto/ReviewDetailResponseDto.java
  src/main/java/com/popflix/domain/review/dto/ReviewListResponseDto.java
  src/main/java/com/popflix/domain/review/dto/ReviewPatchDto.java
  src/main/java/com/popflix/domain/review/dto/ReviewPostDto.java
  src/main/java/com/popflix/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/popflix/domain/review/dto/ReviewSearchResponseDto.java
  src/main/java/com/popflix/domain/review/entity/Comment.java
  src/main/java/com/popflix/domain/review/entity/CommentLike.java
  src/main/java/com/popflix/domain/review/entity/Review.java
  src/main/java/com/popflix/domain/review/entity/ReviewLike.java
  src/main/java/com/popflix/domain/review/enums/LikeType.java
  src/main/java/com/popflix/domain/review/enums/OrderType.java
  src/main/java/com/popflix/domain/review/exception/CommentLikeNotFoundException.java
  src/main/java/com/popflix/domain/review/exception/CommentNotFoundException.java
  src/main/java/com/popflix/domain/review/exception/DuplicateReviewException.java
  src/main/java/com/popflix/domain/review/exception/ErrorResponse.java
  src/main/java/com/popflix/domain/review/exception/ReviewException.java
  src/main/java/com/popflix/domain/review/exception/ReviewExceptionHandler.java
  src/main/java/com/popflix/domain/review/exception/ReviewLikeNotFoundException.java
  src/main/java/com/popflix/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/popflix/domain/review/exception/UnauthorizedReviewAccessException.java
  src/main/java/com/popflix/domain/review/repository/CommentLikeRepository.java
  src/main/java/com/popflix/domain/review/repository/CommentRepository.java
  src/main/java/com/popflix/domain/review/repository/ReviewLikeRepository.java
  src/main/java/com/popflix/domain/review/repository/ReviewRepository.java
  src/main/java/com/popflix/domain/review/service/CommentService.java
  src/main/java/com/popflix/domain/review/service/ReviewService.java
  src/main/java/com/popflix/domain/review/service/impl/CommentServiceImpl.java
  src/main/java/com/popflix/domain/review/service/impl/ReviewServiceImpl.java
Labels: ✨ Feat

#14 feat : 포토리뷰 기능 구현
  src/main/java/com/popflix/domain/photoreview/controller/PhotoReviewCommentController.java
  src/main/java/com/popflix/domain/photoreview/controller/PhotoReviewController.java
  src/main/java/com/popflix/domain/photoreview/controller/PhotoReviewReplyController.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewCommentPatchDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewCommentPostDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewCommentResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewDetailResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewListResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewPatchDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewPostDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewReplyPatchDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewReplyPostDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewReplyResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewSearchResponseDto.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReview.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewComment.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewCommentLike.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewLike.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewReply.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReviewReplyLike.java
  src/main/java/com/popflix/domain/photoreview/enums/PhotoReviewLikeType.java
  src/main/java/com/popflix/domain/photoreview/enums/PhotoReviewOrderType.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewCommentLikeNotFoundException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewCommentNotFoundException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewErrorResponse.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewExceptionHandler.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewImageProcessingException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewLikeNotFoundException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewNotFoundException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewReplyLikeNotFoundException.java
  src/main/java/com/popflix/domain/photoreview/exception/PhotoReviewReplyNotFoundException.java
  src/main/java/com/popflix/domain/photoreview/exception/UnauthorizedPhotoReviewAccessException.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewCommentLikeRepository.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewCommentRepository.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewLikeRepository.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewReplyLikeRepository.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewReplyRepository.java
  src/main/java/com/popflix/domain/photoreview/repository/PhotoReviewRepository.java
  src/main/java/com/popflix/domain/photoreview/service/PhotoReviewCommentService.java
  src/main/java/com/popflix/domain/photoreview/service/PhotoReviewReplyService.java
  src/main/java/com/popflix/domain/photoreview/service/PhotoReviewService.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewCommentServiceImpl.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewReplyServiceImpl.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewServiceImpl.java
Labels: ✨ Feat

#15 feat : 신고 기능 구현
  src/main/java/com/popflix/domain/report/controller/ReportController.java
  src/main/java/com/popflix/domain/report/dto/ReportDetailResponseDto.java
  src/main/java/com/popflix/domain/report/dto/ReportListResponseDto.java
  src/main/java/com/popflix/domain/report/dto/ReportPostDto.java
  src/main/java/com/popflix/domain/report/dto/ReportResponseDto.java
  src/main/java/com/popflix/domain/report/entity/Report.java
  src/main/java/com/popflix/domain/report/enums/ReportReason.java
  src/main/java/com/popflix/domain/report/enums/ReportStatus.java
  src/main/java/com/popflix/domain/report/exception/DuplicateReportException.java
  src/main/java/com/popflix/domain/report/exception/ReportException.java
  src/main/java/com/popflix/domain/report/exception/ReportExceptionHandler.java
  src/main/java/com/popflix/domain/report/exception/ReportNotFoundException.java
  src/main/java/com/popflix/domain/report/repository/ReportRepository.java
  src/main/java/com/popflix/domain/report/service/ReportService.java
  src/main/java/com/popflix/domain/report/service/impl/ReportServiceImpl.java
Labels: ✨ Feat

#17 Feat: 영화 세부조회 api 구현
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/dto/GetCreditsResponseDto.java
  src/main/java/com/popflix/domain/movie/dto/GetDetailsResponseDto.java
  src/main/java/com/popflix/domain/movie/dto/GetMovieListResponseDto.java
  src/main/java/com/popflix/domain/movie/dto/GetTMDBDetailsResponseDto.java
  src/main/java/com/popflix/domain/movie/dto/SimpleDto.java
  src/main/java/com/popflix/domain/movie/dto/SimpleVideoDto.java
  src/main/java/com/popflix/domain/movie/repository/MovieLikeRepository.java
  src/main/java/com/popflix/domain/movie/repository/MovieRepository.java
  src/main/java/com/popflix/domain/movie/service/MovieService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieApiServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieLikeServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/RatingServiceImpl.java
Labels: ✨ Feat

#19 chore : build.gradle 수정
  build.gradle
  src/main/java/com/popflix/domain/review/service/impl/CommentServiceImpl.java
Labels: ✏️Chore

#20 Feat: 영화 추천 기능 api 구현
  src/main/java/com/popflix/domain/movie/controller/MovieController.java
  src/main/java/com/popflix/domain/movie/dto/GetRecommendedMovieResponseDto.java
  src/main/java/com/popflix/domain/movie/repository/MovieRepository.java
  src/main/java/com/popflix/domain/movie/service/MovieApiService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieApiServiceImpl.java
  src/main/java/com/popflix/domain/user/entity/UserGenre.java
  src/main/java/com/popflix/domain/user/repository/UserGenreRepository.java
Labels: ✨ Feat

#23 feat : 로컬 환경 docker compose 구성
  .gitignore
  Dockerfile
  docker-compose.yml
  gradlew
  src/main/resources/application.properties
Labels: ✨ Feat

#24 refactor : BaseSoftDeleteEntity 수정
  src/main/java/com/popflix/common/entity/BaseSoftDeleteEntity.java
Labels: 🚀 Refactor

#26 Feat: 로그인/회원가입 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/popflix/auth/controller/AuthController.java
  src/main/java/com/popflix/auth/dto/AuthResponse.java
  src/main/java/com/popflix/auth/dto/SocialLoginRequestDto.java
  src/main/java/com/popflix/auth/dto/SocialLoginResponseDto.java
  src/main/java/com/popflix/auth/dto/SocialRegisterRequestDto.java
  src/main/java/com/popflix/auth/service/CustomOAuth2UserService.java
  src/main/java/com/popflix/auth/service/RefreshTokenService.java
  src/main/java/com/popflix/auth/service/SocialAuthService.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewCommentServiceImpl.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewReplyServiceImpl.java
  src/main/java/com/popflix/domain/user/entity/User.java
  src/main/java/com/popflix/domain/user/repository/UserRepository.java
  src/main/java/com/popflix/global/config/OAuth2Config.java
  src/main/java/com/popflix/global/config/RedisConfig.java
  src/main/java/com/popflix/global/config/SecurityConfig.java
  src/main/java/com/popflix/global/exception/SocialLoginException.java
  src/main/java/com/popflix/global/filter/JwtFilter.java
  src/main/java/com/popflix/global/jwt/JwtUtil.java
Labels: ✨ Feat

#27 refactor : 포토리뷰 이미지 파일 방식 변경
  build.gradle
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewDetailResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewListResponseDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewPatchDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewPostDto.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewResponseDto.java
  src/main/java/com/popflix/domain/photoreview/entity/PhotoReview.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewCommentServiceImpl.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewReplyServiceImpl.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewServiceImpl.java
  src/main/java/com/popflix/domain/report/service/impl/ReportServiceImpl.java
  src/main/java/com/popflix/domain/review/service/impl/CommentServiceImpl.java
  src/main/java/com/popflix/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/popflix/global/config/S3Config.java
  src/main/java/com/popflix/global/exception/FileDeleteException.java
  src/main/java/com/popflix/global/exception/FileUploadException.java
  src/main/java/com/popflix/global/service/S3Service.java
Labels: 🚀 Refactor

#29 feat : 오늘 받은 알림과 이전 알림으로 그룹화
  src/main/java/com/popflix/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/popflix/domain/notification/entity/Notification.java
  src/main/java/com/popflix/domain/notification/event/dto/ReviewCreatedEvent.java
  src/main/java/com/popflix/domain/notification/event/listener/ReviewEventListener.java
  src/main/java/com/popflix/domain/notification/repository/NotificationRepository.java
  src/main/java/com/popflix/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/com/popflix/domain/photoreview/service/impl/PhotoReviewServiceImpl.java
  src/main/java/com/popflix/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/popflix/global/config/MailConfig.java
Labels: ✨ Feat

#30 remove : 회원가입 구현 삭제
  build.gradle
  src/main/java/com/popflix/auth/controller/AuthController.java
  src/main/java/com/popflix/auth/dto/AuthResponse.java
  src/main/java/com/popflix/auth/dto/SocialLoginRequestDto.java
  src/main/java/com/popflix/auth/dto/SocialLoginResponseDto.java
  src/main/java/com/popflix/auth/dto/SocialRegisterRequestDto.java
  src/main/java/com/popflix/auth/service/CustomOAuth2UserService.java
  src/main/java/com/popflix/auth/service/RefreshTokenService.java
  src/main/java/com/popflix/auth/service/SocialAuthService.java
  src/main/java/com/popflix/domain/photoreview/controller/PhotoReviewController.java
  src/main/java/com/popflix/domain/photoreview/dto/PhotoReviewPostDto.java
  src/main/java/com/popflix/domain/user/test.java
  src/main/java/com/popflix/global/config/OAuth2Config.java
  src/main/java/com/popflix/global/config/SecurityConfig.java
  src/main/java/com/popflix/global/filter/JwtFilter.java
  src/main/java/com/popflix/global/jwt/JwtUtil.java
Labels: remove

#31 refactor : User Entity 수정
  src/main/java/com/popflix/domain/user/entity/User.java
Labels: 🚀 Refactor

#25 Feat: 워치리스트 API 구현
  src/main/java/com/popflix/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/popflix/domain/movie/dto/AddMovieRequestDto.java
  src/main/java/com/popflix/domain/movie/dto/GetRatingResponseDto.java
  src/main/java/com/popflix/domain/movie/entity/Cast.java
  src/main/java/com/popflix/domain/movie/entity/Director.java
  src/main/java/com/popflix/domain/movie/entity/MovieCast.java
  src/main/java/com/popflix/domain/movie/entity/MovieDirector.java
  src/main/java/com/popflix/domain/movie/entity/MovieLike.java
  src/main/java/com/popflix/domain/movie/repository/MovieRepository.java
  src/main/java/com/popflix/domain/movie/repository/RatingRepository.java
  src/main/java/com/popflix/domain/movie/service/MovieService.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieApiServiceImpl.java
  src/main/java/com/popflix/domain/movie/service/impl/MovieServiceImpl.java
  src/main/java/com/popflix/domain/personality/entity/Genre.java
  src/main/java/com/popflix/domain/storage/controller/StorageController.java
  src/main/java/com/popflix/domain/storage/dto/CreateStorageRequestDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageCreatorResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageDetail2ResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageDetailResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageMovieResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/GetStorageResponseDto.java
  src/main/java/com/popflix/domain/storage/dto/UpdateStorageRequestDto.java
  src/main/java/com/popflix/domain/storage/entity/Storage.java
  src/main/java/com/popflix/domain/storage/entity/StorageLike.java
  src/main/java/com/popflix/domain/storage/exception/AccessStorageDeniedException.java
  src/main/java/com/popflix/domain/storage/exception/DuplicateMovieException.java
  src/main/java/com/popflix/domain/storage/exception/DuplicateStorageNameException.java
  src/main/java/com/popflix/domain/storage/exception/StorageNotFoundException.java
  src/main/java/com/popflix/domain/storage/repository/MovieStorageRepository.java
  src/main/java/com/popflix/domain/storage/repository/StorageLikeRepository.java
  src/main/java/com/popflix/domain/storage/repository/StorageRepository.java
  src/main/java/com/popflix/domain/storage/service/StorageLikeService.java
  src/main/java/com/popflix/domain/storage/service/StorageService.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageLikeServiceImpl.java
  src/main/java/com/popflix/domain/storage/service/impl/StorageServiceImpl.java
Labels: ✨ Feat
